name: Create Issue
on:
  repository_dispatch:
    types: [create-issue]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Issue
        uses: actions/github-script@v6
        with:
          token: ${{ github.token }}
          script: |
            const { title, body, labels } = github.event.client_payload;
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });
            const existingIssue = issues.data.find(issue => issue.title === title);
            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: labels,
              });
              console.log('Issue created');
            } else {
              console.log('Issue already exists');
            }
